[2024-10-13T09:02:10.340+0000] {processor.py:186} INFO - Started process (PID=76) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:02:10.357+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:02:10.373+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:02:10.370+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:02:11.096+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:02:11.033+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:02:11.143+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/stock_scraper_dag.py:10 SyntaxWarning: invalid escape sequence '\s'
[2024-10-13T09:02:11.150+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:02:11.502+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 1.256 seconds
[2024-10-13T09:02:45.471+0000] {processor.py:186} INFO - Started process (PID=140) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:02:45.474+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:02:45.478+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:02:45.478+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:02:45.515+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:02:45.505+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:02:45.519+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:02:45.581+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.117 seconds
[2024-10-13T09:03:17.014+0000] {processor.py:186} INFO - Started process (PID=199) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:03:17.047+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:03:17.053+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:03:17.052+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:03:17.113+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:03:17.104+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:03:17.120+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:03:17.206+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.221 seconds
[2024-10-13T09:03:48.885+0000] {processor.py:186} INFO - Started process (PID=263) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:03:48.889+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:03:48.898+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:03:48.897+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:03:49.075+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:03:49.022+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:03:49.102+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:03:49.187+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.320 seconds
[2024-10-13T09:04:23.797+0000] {processor.py:186} INFO - Started process (PID=324) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:04:23.800+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:04:23.836+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:04:23.833+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:04:23.969+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:04:23.906+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:04:23.981+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:04:24.100+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.445 seconds
[2024-10-13T09:04:54.280+0000] {processor.py:186} INFO - Started process (PID=385) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:04:54.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:04:54.285+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:04:54.284+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:04:54.314+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:04:54.307+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:04:54.318+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:04:54.357+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.083 seconds
[2024-10-13T09:05:25.044+0000] {processor.py:186} INFO - Started process (PID=448) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:05:25.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:05:25.050+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:05:25.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:05:25.079+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:05:25.072+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:05:25.083+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:05:25.126+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.086 seconds
[2024-10-13T09:05:55.276+0000] {processor.py:186} INFO - Started process (PID=508) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:05:55.285+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:05:55.292+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:05:55.292+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:05:55.342+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:05:55.333+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:05:55.347+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:05:55.402+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.137 seconds
[2024-10-13T09:06:25.529+0000] {processor.py:186} INFO - Started process (PID=570) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:06:25.531+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:06:25.535+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:06:25.534+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:06:25.562+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:06:25.555+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:06:25.565+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:06:25.593+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.070 seconds
[2024-10-13T09:06:55.675+0000] {processor.py:186} INFO - Started process (PID=631) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:06:55.676+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:06:55.683+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:06:55.682+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:06:55.722+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:06:55.713+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:06:55.725+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:06:55.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.092 seconds
[2024-10-13T09:07:25.931+0000] {processor.py:186} INFO - Started process (PID=695) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:07:25.933+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:07:25.939+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:07:25.938+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:07:26.038+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:07:26.013+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:07:26.042+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:07:26.112+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.196 seconds
[2024-10-13T09:07:56.279+0000] {processor.py:186} INFO - Started process (PID=758) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:07:56.282+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:07:56.293+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:07:56.292+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:07:56.348+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:07:56.333+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:07:56.353+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:07:56.390+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.121 seconds
[2024-10-13T09:08:27.062+0000] {processor.py:186} INFO - Started process (PID=821) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:08:27.065+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:08:27.070+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:08:27.069+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:08:27.112+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:08:27.101+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:08:27.116+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:08:27.165+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.120 seconds
[2024-10-13T09:08:57.870+0000] {processor.py:186} INFO - Started process (PID=884) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:08:57.876+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:08:57.884+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:08:57.883+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:08:57.968+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:08:57.939+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:08:57.975+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:08:58.073+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.246 seconds
[2024-10-13T09:09:28.437+0000] {processor.py:186} INFO - Started process (PID=938) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:09:28.440+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:09:28.446+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:09:28.445+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:09:28.507+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:09:28.492+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:09:28.516+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:09:28.581+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.161 seconds
[2024-10-13T09:09:59.191+0000] {processor.py:186} INFO - Started process (PID=998) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:09:59.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:09:59.195+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:09:59.194+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:09:59.219+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:09:59.213+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:09:59.222+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:09:59.241+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.055 seconds
[2024-10-13T09:10:29.552+0000] {processor.py:186} INFO - Started process (PID=1061) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:10:29.553+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:10:29.556+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:10:29.555+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:10:29.583+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:10:29.576+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:10:29.585+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:10:29.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.063 seconds
[2024-10-13T09:11:00.536+0000] {processor.py:186} INFO - Started process (PID=1124) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:11:00.538+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:11:00.543+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:11:00.543+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:11:00.581+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:11:00.572+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:11:00.586+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:11:00.725+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.201 seconds
[2024-10-13T09:11:31.519+0000] {processor.py:186} INFO - Started process (PID=1187) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:11:31.520+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:11:31.522+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:11:31.522+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:11:31.544+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:11:31.539+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:11:31.546+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:11:31.566+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.052 seconds
[2024-10-13T09:12:02.127+0000] {processor.py:186} INFO - Started process (PID=1250) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:12:02.129+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:12:02.131+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:12:02.131+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:12:02.167+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:12:02.158+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:12:02.171+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:12:02.201+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.079 seconds
[2024-10-13T09:12:32.531+0000] {processor.py:186} INFO - Started process (PID=1313) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:12:32.533+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:12:32.537+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:12:32.536+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:12:32.575+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:12:32.565+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:12:32.578+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:12:32.625+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.102 seconds
[2024-10-13T09:13:03.006+0000] {processor.py:186} INFO - Started process (PID=1371) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:13:03.014+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:13:03.031+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:13:03.020+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:13:03.165+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:13:03.133+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:13:03.174+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:13:03.305+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.316 seconds
[2024-10-13T09:13:33.633+0000] {processor.py:186} INFO - Started process (PID=1434) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:13:33.636+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:13:33.644+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:13:33.644+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:13:33.700+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:13:33.689+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:13:33.708+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:13:33.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.141 seconds
[2024-10-13T09:14:04.010+0000] {processor.py:186} INFO - Started process (PID=1497) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:14:04.012+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:14:04.014+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:14:04.014+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:14:04.041+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:14:04.035+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:14:04.044+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:14:04.071+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.066 seconds
[2024-10-13T09:14:34.550+0000] {processor.py:186} INFO - Started process (PID=1560) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:14:34.552+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:14:34.561+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:14:34.560+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:14:34.601+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:14:34.592+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:14:34.609+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:14:34.651+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.112 seconds
[2024-10-13T09:15:04.848+0000] {processor.py:186} INFO - Started process (PID=1623) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:15:04.850+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:15:04.859+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:15:04.858+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:15:04.898+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:15:04.888+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:15:04.902+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:15:04.941+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.108 seconds
[2024-10-13T09:15:35.701+0000] {processor.py:186} INFO - Started process (PID=1686) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:15:35.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:15:35.706+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:15:35.705+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:15:35.769+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:15:35.762+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:15:35.772+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:15:35.811+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.119 seconds
[2024-10-13T09:16:06.382+0000] {processor.py:186} INFO - Started process (PID=1749) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:16:06.385+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:16:06.393+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:16:06.392+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:16:06.427+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:16:06.418+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:16:06.434+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:16:06.484+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.119 seconds
[2024-10-13T09:16:36.980+0000] {processor.py:186} INFO - Started process (PID=1812) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:16:36.982+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:16:36.987+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:16:36.986+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:16:37.019+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:16:37.011+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:16:37.022+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:16:37.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.083 seconds
[2024-10-13T09:17:07.836+0000] {processor.py:186} INFO - Started process (PID=1875) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:17:07.911+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:17:07.962+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:17:07.962+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:17:07.973+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:17:07.969+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:17:07.974+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:17:08.010+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.179 seconds
[2024-10-13T09:17:38.250+0000] {processor.py:186} INFO - Started process (PID=1938) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:17:38.252+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:17:38.255+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:17:38.255+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:17:38.288+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:17:38.279+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:17:38.291+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:17:38.312+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.067 seconds
[2024-10-13T09:18:08.927+0000] {processor.py:186} INFO - Started process (PID=2001) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:18:08.929+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:18:08.932+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:18:08.932+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:18:08.958+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:18:08.953+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:18:08.959+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:18:08.976+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.055 seconds
[2024-10-13T09:18:39.122+0000] {processor.py:186} INFO - Started process (PID=2064) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:18:39.124+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:18:39.129+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:18:39.129+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:18:39.248+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:18:39.233+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:18:39.250+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:18:39.269+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.152 seconds
[2024-10-13T09:19:10.006+0000] {processor.py:186} INFO - Started process (PID=2127) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:19:10.008+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:19:10.011+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:19:10.011+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:19:10.042+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:19:10.034+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:19:10.046+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:19:10.079+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.080 seconds
[2024-10-13T09:19:40.783+0000] {processor.py:186} INFO - Started process (PID=2190) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:19:40.789+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:19:40.813+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:19:40.812+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:19:41.097+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:19:41.081+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:19:41.102+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:19:41.347+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.605 seconds
[2024-10-13T09:20:11.487+0000] {processor.py:186} INFO - Started process (PID=2253) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:20:11.489+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:20:11.494+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:20:11.493+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:20:11.525+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:20:11.518+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:20:11.528+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:20:11.572+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.090 seconds
[2024-10-13T09:20:42.169+0000] {processor.py:186} INFO - Started process (PID=2316) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:20:42.170+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:20:42.173+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:20:42.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:20:42.195+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:20:42.189+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:20:42.197+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:20:42.222+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.059 seconds
[2024-10-13T09:21:12.469+0000] {processor.py:186} INFO - Started process (PID=2379) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:21:12.471+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:21:12.475+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:21:12.474+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:21:12.503+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:21:12.497+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:21:12.505+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:21:12.525+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.060 seconds
[2024-10-13T09:21:42.836+0000] {processor.py:186} INFO - Started process (PID=2443) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:21:42.839+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:21:42.843+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:21:42.843+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:21:42.869+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:21:42.863+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:21:42.875+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:21:42.897+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.066 seconds
[2024-10-13T09:22:13.668+0000] {processor.py:186} INFO - Started process (PID=2506) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:22:13.678+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:22:13.685+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:22:13.685+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:22:13.731+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:22:13.718+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:22:13.748+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:22:13.787+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.125 seconds
[2024-10-13T09:22:44.291+0000] {processor.py:186} INFO - Started process (PID=2569) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:22:44.293+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:22:44.298+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:22:44.298+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:22:44.328+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:22:44.321+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:22:44.331+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:22:44.355+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.069 seconds
[2024-10-13T09:23:14.734+0000] {processor.py:186} INFO - Started process (PID=2632) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:23:14.736+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:23:14.739+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:23:14.739+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:23:14.771+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:23:14.763+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:23:14.773+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:23:14.813+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.088 seconds
[2024-10-13T09:23:45.000+0000] {processor.py:186} INFO - Started process (PID=2695) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:23:45.002+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:23:45.005+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:23:45.005+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:23:45.029+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:23:45.023+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:23:45.033+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:23:45.054+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.062 seconds
[2024-10-13T09:24:15.966+0000] {processor.py:186} INFO - Started process (PID=2759) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:24:15.971+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:24:15.992+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:24:15.991+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:24:16.338+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:24:16.223+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:24:16.353+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:24:16.503+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.570 seconds
[2024-10-13T09:24:46.918+0000] {processor.py:186} INFO - Started process (PID=2821) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:24:46.922+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:24:46.930+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:24:46.929+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:24:47.006+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:24:46.997+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:24:47.011+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:24:47.067+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.167 seconds
[2024-10-13T09:25:17.715+0000] {processor.py:186} INFO - Started process (PID=2885) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:25:17.718+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:25:17.724+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:25:17.723+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:25:17.759+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:25:17.750+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:25:17.763+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:25:17.795+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.093 seconds
[2024-10-13T09:25:48.703+0000] {processor.py:186} INFO - Started process (PID=2954) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:25:48.705+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:25:48.707+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:25:48.707+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:25:48.732+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:25:48.725+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:25:48.735+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:25:48.753+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.055 seconds
[2024-10-13T09:26:19.574+0000] {processor.py:186} INFO - Started process (PID=3016) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:26:19.576+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:26:19.590+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:26:19.589+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:26:19.717+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:26:19.686+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:26:19.725+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:26:19.773+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.222 seconds
[2024-10-13T09:26:50.675+0000] {processor.py:186} INFO - Started process (PID=3079) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:26:50.714+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:26:50.731+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:26:50.730+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:26:50.785+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:26:50.763+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:26:50.807+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:26:50.847+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.190 seconds
[2024-10-13T09:27:23.408+0000] {processor.py:186} INFO - Started process (PID=3136) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:27:23.455+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:27:23.504+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:27:23.503+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:27:23.677+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:27:23.632+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:27:23.715+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:27:23.753+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.362 seconds
[2024-10-13T09:27:55.851+0000] {processor.py:186} INFO - Started process (PID=3198) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:27:55.857+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:27:55.864+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:27:55.863+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:27:55.925+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:27:55.910+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:27:55.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:27:55.976+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.137 seconds
[2024-10-13T09:28:26.235+0000] {processor.py:186} INFO - Started process (PID=3261) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:28:26.237+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:28:26.245+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:28:26.244+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:28:26.294+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:28:26.284+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:28:26.299+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:28:26.350+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.133 seconds
[2024-10-13T09:28:56.462+0000] {processor.py:186} INFO - Started process (PID=3324) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:28:56.464+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:28:56.469+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:28:56.468+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:28:56.502+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:28:56.492+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:28:56.506+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:28:56.557+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.104 seconds
[2024-10-13T09:29:26.649+0000] {processor.py:186} INFO - Started process (PID=3387) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:29:26.650+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:29:26.653+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:29:26.652+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:29:26.677+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:29:26.673+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:29:26.680+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:29:26.710+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.067 seconds
[2024-10-13T09:29:57.246+0000] {processor.py:186} INFO - Started process (PID=3445) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:29:57.249+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-13T09:29:57.254+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:29:57.253+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:29:57.294+0000] {logging_mixin.py:190} INFO - [2024-10-13T09:29:57.284+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-13T09:29:57.299+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-13T09:29:57.340+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.111 seconds
